### ISSUE TITLE
Not working HP probook Linux mint

### ISSUE THREAD

**Issue by Timtonix** [SpookySkeletons/hp_bios_unlocker#2]
Hey there
I installed your script on a flash drive Linux mint.
But I've got these errors ![image](https://github.com/SpookySkeletons/hp_bios_unlocker/assets/71769881/8380a09e-30b3-444f-8ac5-2054f3dd73b0)

I really need to access bios settings to install Linux on the computer
Thanks for your response 
Timtonix

**Comment by SpookySkeletons** [comment]
It doesn't operate the on the machine, you must read the ROM out and flash it back.
